### ISSUE TITLE
Is this project maintained anymore?

### ISSUE THREAD

**Issue by thomas-zmo08179** [jnko/SimpleDatabaseBackup#12]
Is this project maintained anymore?

**Comment by jnko** [comment]
Yes, whenever I've some rare sparetime..

**Comment by jgehrcke** [comment]
I came here to say thank you @jnko! I have discovered your plugin today and mainly based on your nice README I think it's very solid. I am using KeePass day to day cross-platform and sync the database file via syncthing. I think this plugin fits quite nicely, adding protection against human error. Thanks!
